name: GlowingCube
favicon: null
layout_spectrum: 0.19175664894282818
typography_spectrum: 0.9572286834008992
title: Glowing Cube creative studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.0625
  lightness: 0.07296807505190372
  saturation: 1
  rhythmicContrast: 0.45470423880033195
purpose: []
